### ISSUE TITLE
Ei mano, eu vi que esse é seu primeiro painel, mas eu tô com um problema.

### ISSUE THREAD

**Issue by Illan01345** [kvgnx54/ghostpanel#1]
Quando executo o "python main.py" aparece:
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/ghostpanel/main.py", line 12, in <module>                                              from requests import get                                    File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/util/__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/util/connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/util/wait.py", line 1, in <module>
    from .selectors import (
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/urllib3/util/selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/data/data/com.termux/files/usr/lib/python3.11/collections/__init__.py)

**Obs: to com o python 3.11.8 e o pip 24.0 no Termux 0.118.0**

Se conseguir corrigir aí, agradeço, valeu.
![Uploading Screenshot_2024-02-18-12-56-17-817_com.termux.jpg…]()

**Comment by kvgnx54** [comment]
a algum tempo atrás eu atualizei esse painel, deixei um pouco mais bonito e otimizado. Você pode tentar reinstalar o painel para corrigir esse erro, mas não sei se vai funcionar
